# Generated by Django 5.1.6 on 2025-03-21 00:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slogan', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('image', models.ImageField(help_text='Image size: 1024x567', upload_to='sliders/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('show_button', models.BooleanField(default=True)),
                ('button_text', models.CharField(default='Read More', max_length=50)),
                ('language', models.CharField(choices=[('en', 'English'), ('de', 'German')], default='en', max_length=2)),
            ],
        ),
    ]
