# Generated by Django 5.1.6 on 2025-03-21 03:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FewWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('section_a', models.TextField(max_length=300)),
                ('section_b', models.TextField(max_length=300)),
                ('image', models.ImageField(help_text='Image size: 1024x567', upload_to='few_words/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('language', models.CharField(choices=[('en', 'English'), ('de', 'Deutsch')], default='en', max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='slider',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'Deutsch')], default='en', max_length=2),
        ),
    ]
