# Generated by Django 5.1.6 on 2025-03-21 03:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_fewwords_alter_slider_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('image', models.ImageField(help_text='Image size: 80x80, PNG format, Transparent background', upload_to='services/', validators=[django.core.validators.FileExtensionValidator(['png'])])),
                ('language', models.CharField(choices=[('en', 'English'), ('de', 'Deutsch')], default='en', max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.AlterModelOptions(
            name='fewwords',
            options={'verbose_name_plural': 'Few Words'},
        ),
        migrations.AlterField(
            model_name='fewwords',
            name='image',
            field=models.ImageField(help_text='Image size: 1920x662', upload_to='few_words/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
    ]
