# Generated by Django 5.1.6 on 2025-03-21 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_services_alter_fewwords_options_alter_fewwords_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtShowcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_a', models.TextField(max_length=300)),
                ('section_b', models.TextField(max_length=300)),
                ('language', models.CharField(choices=[('en', 'English'), ('de', 'Deutsch')], default='en', max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Art Showcase',
            },
        ),
    ]
