# Generated by Django 5.1.6 on 2025-03-21 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_artshowcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artshowcase',
            name='section_b',
            field=models.TextField(max_length=500),
        ),
    ]
