# Generated by Django 5.1.6 on 2025-03-21 18:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('section_a', models.TextField(max_length=300)),
                ('section_b', models.TextField(max_length=300)),
                ('image_a', models.ImageField(help_text='Image size: 900x584', upload_to='advantages/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('image_b', models.ImageField(help_text='Image size: 1024x683', upload_to='advantages/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('image_c', models.ImageField(help_text='Image size: 1000x667', upload_to='advantages/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('quotation', models.CharField(max_length=200)),
                ('language', models.CharField(choices=[('en', 'English'), ('de', 'Deutsch')], default='en', max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(help_text='Image size: 1920x1280', upload_to='artists/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='fewwords',
            name='image',
            field=models.ImageField(help_text='Image size: 1920x662', upload_to='few_words/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(help_text='Image size: 1024x567', upload_to='sliders/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
