# Generated by Django 5.1.6 on 2025-03-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0007_advantage_alter_artist_image_alter_fewwords_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advantage',
            name='title',
            field=models.TextField(max_length=200),
        ),
    ]
