# Generated by Django 5.1.6 on 2025-03-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0008_alter_advantage_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advantage',
            name='section_a',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='advantage',
            name='section_b',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='advantage',
            name='title',
            field=models.TextField(max_length=300),
        ),
    ]
