# Generated by Django 5.1.6 on 2025-03-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0011_gallery_include_in_home_gallery_include_in_showcase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('suffix', models.CharField(default='', help_text='Example: "+" or "%" or "years"', max_length=50)),
                ('language', models.CharField(choices=[('en', 'English'), ('de', 'Deutsch')], default='en', max_length=2)),
            ],
        ),
    ]
