# Generated by Django 5.1.6 on 2025-03-22 12:20

import django.core.validators
import public.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0012_fact'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=250)),
                ('image_a', models.ImageField(help_text='Image size: 1920x1280', upload_to='why_choose_us/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('image_b', models.ImageField(help_text='Image size: 1920x1280', upload_to='why_choose_us/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('language', models.CharField(choices=[('en', 'English'), ('de', 'Deutsch')], default='en', max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Why Choose Us',
            },
            bases=(models.Model, public.mixins.ImageCleanupMixin),
        ),
    ]
