# Generated by Django 5.1.6 on 2025-03-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0014_remove_whychooseus_description_whychooseus_section_a_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=300)),
                ('answer', models.TextField(max_length=500)),
                ('language', models.CharField(choices=[('en', 'English'), ('de', 'Deutsch')], default='en', max_length=2)),
            ],
        ),
    ]
