# Generated by Django 5.1.6 on 2025-03-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0016_alter_faq_options_alter_faq_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fewwords',
            name='section_b',
            field=models.TextField(max_length=600),
        ),
    ]
