# Generated by Django 5.1.6 on 2025-03-22 14:06

import django.core.validators
import public.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0017_alter_fewwords_section_b'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Image size: 1920x1280', upload_to='header_images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
            ],
            bases=(models.Model, public.mixins.ImageCleanupMixin),
        ),
    ]
